### ISSUE TITLE
add profession field

### ISSUE THREAD

**Issue by thraxil** [thraxil/spokehub#80]
assume we're getting rid of 'discipline1' and 'discipline2' fields while we're at it

**Comment by thraxil** [comment]
schema changes so a `make migrate` will be necessary again.

**Comment by argoncobalt** [comment]
Done and done.

**Comment by argoncobalt** [comment]
Where is the new signup form? I tried entering http://162.243.25.178/signupform/ and received an error, even after the migration run. Please see the attached screenshot.
